set nocompatible

""""""""""""""""""""""""""""""
" Additional plugin dirs
""""""""""""""""""""""""""""""

set rtp+=~/.vim/bundle/nerdcommenter
set rtp+=~/.vim/bundle/pyflakes
set rtp+=~/.vim/bundle/tasklist


""""""""""""""""""""""""""""""
"
""""""""""""""""""""""""""""""

set backspace=indent,eol,start  " allow backspacing over everything in insert mode

set nobackup                    " no backuping of edited file
set history=50                  " keep 50 lines of command line history
set ruler                       " show the cursor position all the time
set showcmd                     " display incomplete commands
set incsearch                   " do incremental searching

set shiftwidth=4
set tabstop=4
set expandtab

set number
set encoding=utf-8
set nowrap

syntax on
set hlsearch

set showmatch                   " show matching (), [], ...

"
" Show whitespace (to turn off: 'set nolist')
"
set listchars=trail:~,tab:>-
set list

"
" Enable file type detection.
"
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
"
" Also load indent files, to automatically do language-dependent indenting.
"
filetype plugin indent on

"
" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
"
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

"
" Settings for Netrw Directory Listing
"
let g:netrw_liststyle=3
let g:netrw_sort_sequence='[\/]$,*'


""""""""""""""""""""
" Plugins
""""""""""""""""""""

"
" pyflakes
"
highlight SpellBad cterm=undercurl,bold ctermbg=NONE
