set nocompatible

""""""""""""""""""""""""""""""
" Additional plugin dirs
""""""""""""""""""""""""""""""

set rtp+=~/.vim/bundle/nerdcommenter
set rtp+=~/.vim/bundle/pyflakes
set rtp+=~/.vim/bundle/tasklist


""""""""""""""""""""""""""""""
"
""""""""""""""""""""""""""""""

set backspace=indent,eol,start  " allow backspacing over everything in insert mode

set nobackup                    " no backuping of edited file
set history=50                  " keep 50 lines of command line history
set showcmd                     " display incomplete commands
set ruler                       " show the cursor position all the time
set nowrap

set incsearch                   " do incremental searching
set hlsearch

set shiftwidth=4
set tabstop=4
set expandtab

set encoding=utf-8

set number
set showmatch                   " show matching (), [], ...

syntax on

"
" Show whitespace (to turn off: 'set nolist')
"
set listchars=trail:~,tab:>-
set list

"
" Enable file type detection.
"
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
"
" Also load indent files, to automatically do language-dependent indenting.
"
filetype plugin indent on

"
" For all text files show right margin at 80 column
"
autocmd FileType text setlocal cc=80

"
" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
"
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

"
" Spelling (turn off: set nospell)
"
autocmd FileType text set spell
set spelllang=en

"
" Settings for Netrw Directory Listing
"
let g:netrw_liststyle=3
let g:netrw_sort_sequence='[\/]$,*'

"
" Turn on sytax highlightning for SConstruct files
"
if @% == "SConstruct" || @% == "SConscript"
    set syntax=python
endif


""""""""""""""""""""
" Clang-Format
""""""""""""""""""""

map <C-K> :pyf ~/bin/clang-format.py<cr>
imap <C-K> <c-o>:pyf ~/bin/clang-format.py<cr>


""""""""""""""""""""
" Plugins
""""""""""""""""""""

"
" pyflakes
"
" Change "SpellBad" style when opening any python file.
"
autocmd FileType python highlight SpellBad cterm=undercurl,bold ctermbg=NONE
